Punto 4

In [1]:
import numpy as np

In [2]:
A= np.array(
    [
        [1,-3,-2],
        [2,-4,-3],
        [-3,6,8]
    ]
)
# otra manera es A= np.array([[1,-3,-2],[2,-4,-3],[-3,6,8]])

In [3]:
print(A)

[[ 1 -3 -2]
 [ 2 -4 -3]
 [-3  6  8]]


In [4]:
b= np.array(
    [
        [6],
        [8],
        [-5]
    ]
)
# otra manera es b= np.array([[6],[6],[-5]])

In [5]:
print(b)

[[ 6]
 [ 8]
 [-5]]


In [6]:
x=np.linalg.solve(A,b)

In [7]:
print(x)

[[ 1.]
 [-3.]
 [ 2.]]


In [8]:
A.dot(x)

array([[ 6.],
       [ 8.],
       [-5.]])

In [9]:
# A*x multiplica coordenada por coordenada

In [10]:
A.dot(x)-b

array([[ 1.77635684e-15],
       [-8.88178420e-16],
       [ 0.00000000e+00]])