
Ejercicio 4

In [33]:
import numpy as np 

A = np.array([[1, -3, -2], [2,-4,-3], [-3,6,8]])
b = np.array([6,8,-5])

print(A)
print(b)

x = np.linalg.solve(A, b.T)
x

[[ 1 -3 -2]
 [ 2 -4 -3]
 [-3  6  8]]
[ 6  8 -5]


array([ 1., -3.,  2.])