In [59]:
import numpy as np
np.set_printoptions(precision = 4, linewidth = 132)
kbasic=np.array([[1,0,-1,0],
                 [0,0,0,0],
                 [-1,0,1,0],
                 [0,0,0,0]])

m=3 #esta informacion debera ser introducida por un .txt CAMBIAR, es el numero de elementos
posicionesnodos=np.array([[0,0],
                         [1,0],
                         [1,1]]) #esta informacion debera ser introducida por un .txt CAMBIAR ,par (x,y)
MC=np.array([[0,1],
             [0,2],
             [1,2]])  #matriz de conectividad de los nodos, debera ser introducida por  .TXT
n=len(posicionesnodos)
A=np.array([10,10,10]) #area de cada elemento debera ser introducida por un .TXT CAMBIAR
E=210e9   #[Pa]

T=np.zeros((4,4))
Ttranspuesta=np.zeros((4,4))


In [58]:
kelemental=[]
kglobal=np.zeros((2*n,2*n))
for i in range(0,m):
    
    nodo1=MC[i,0]
    nodo2=MC[i,1]
    x1=posicionesnodos[nodo1,0]
    y1=posicionesnodos[nodo1,1]
    x2=posicionesnodos[nodo2,0]
    y2=posicionesnodos[nodo2,1]
    L=np.sqrt((x1-x2)**2+(y1-y2)**2)
    c=E*A[i]/L
    klocal=kbasic*c
    angulo=np.arctan2((y2-y1),(x2-x1))
    # ahora hay que cambiar la base de la matriz de rigidez a las coordenadas globales
    cos=np.cos(angulo)
    sen=np.sin(angulo)
    #armo la matriz de rotacion
    T[0,0]=cos 
    T[0,1]=sen
    T[1,0]=-sen
    T[1,1]=cos
    T[2,2]=cos
    T[2,3]=sen
    T[3,2]=-sen
    T[3,3]=cos
    #la matriz transpuesta de rotacion 
    Ttranspuesta[0,0]=cos 
    Ttranspuesta[0,1]=-sen
    Ttranspuesta[1,0]=sen
    Ttranspuesta[1,1]=cos
    Ttranspuesta[2,2]=cos     # usar transpose para hacer las cosas mas facil y no definir a mano las transpuesta 
    Ttranspuesta[2,3]=-sen
    Ttranspuesta[3,2]=sen
    Ttranspuesta[3,3]=cos
    kelemental.append(np.dot(np.dot(Ttranspuesta,klocal),T))
    scale=np.max((np.max(kelemental[-1])))
    kelemental[-1][abs(kelemental[-1]/scale)<1e-9]=0  # receta para filtrar elementos de la matriz ,con la condicion que aparece dentro del parentesis 
    #print(kelemental[-1]/c)
    
    indices_g=np.array([2*nodo1,2*nodo1+1],dtype=int)  #,2*nodo2,2*nodo2+1])
    indices2_g=np.array([2*nodo2,2*nodo2+1],dtype=int) #,2*nodo1,2*nodo1+1])
    #indices3_g=np.array([2*nodo2,2*nodo2+1,2*nodo1,2*nodo1+1])
    #indices4_g=np.array([2*nodo2,2*nodo2+1,2*nodo2,2*nodo2+1])
    
    indices=np.array([0,1],dtype=int) #,2,3])
    indices2=np.array([2,3],dtype=int) #,2*0,2*0+1])
    #indices3=np.array([2*1,2*1+1,2*0,2*0+1])
    #indices4=np.array([2*1,2*1+1,2*1,2*1+1])
    
    kglobal[np.ix_(indices_g,indices_g)]+=kelemental[-1][np.ix_(indices,indices)]
    kglobal[np.ix_(indices_g,indices2_g)]+=kelemental[-1][np.ix_(indices,indices2)]
    kglobal[np.ix_(indices2_g,indices_g)]+=kelemental[-1][np.ix_(indices2,indices)]
    kglobal[np.ix_(indices2_g,indices2_g)]+=kelemental[-1][np.ix_(indices2,indices2)]
    
    print(kglobal)

[[ 2.1e+12  0.0e+00 -2.1e+12  0.0e+00  0.0e+00  0.0e+00]
 [ 0.0e+00  0.0e+00  0.0e+00  0.0e+00  0.0e+00  0.0e+00]
 [-2.1e+12  0.0e+00  2.1e+12  0.0e+00  0.0e+00  0.0e+00]
 [ 0.0e+00  0.0e+00  0.0e+00  0.0e+00  0.0e+00  0.0e+00]
 [ 0.0e+00  0.0e+00  0.0e+00  0.0e+00  0.0e+00  0.0e+00]
 [ 0.0e+00  0.0e+00  0.0e+00  0.0e+00  0.0e+00  0.0e+00]]
[[ 2.8425e+12  7.4246e+11 -2.1000e+12  0.0000e+00 -7.4246e+11 -7.4246e+11]
 [ 7.4246e+11  7.4246e+11  0.0000e+00  0.0000e+00 -7.4246e+11 -7.4246e+11]
 [-2.1000e+12  0.0000e+00  2.1000e+12  0.0000e+00  0.0000e+00  0.0000e+00]
 [ 0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00]
 [-7.4246e+11 -7.4246e+11  0.0000e+00  0.0000e+00  7.4246e+11  7.4246e+11]
 [-7.4246e+11 -7.4246e+11  0.0000e+00  0.0000e+00  7.4246e+11  7.4246e+11]]
[[ 2.8425e+12  7.4246e+11 -2.1000e+12  0.0000e+00 -7.4246e+11 -7.4246e+11]
 [ 7.4246e+11  7.4246e+11  0.0000e+00  0.0000e+00 -7.4246e+11 -7.4246e+11]
 [-2.1000e+12  0.0000e+00  2.1000e+12  0.0000e+00  0.000

In [52]:
kelemental

[array([[2.1e+12, 0.0e+00, 0.0e+00, 0.0e+00],
        [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00],
        [0.0e+00, 0.0e+00, 2.1e+12, 0.0e+00],
        [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00]]),
 array([[7.4246e+11, 7.4246e+11, 0.0000e+00, 0.0000e+00],
        [7.4246e+11, 7.4246e+11, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 7.4246e+11, 7.4246e+11],
        [0.0000e+00, 0.0000e+00, 7.4246e+11, 7.4246e+11]]),
 array([[0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00],
        [0.0e+00, 2.1e+12, 0.0e+00, 0.0e+00],
        [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00],
        [0.0e+00, 0.0e+00, 0.0e+00, 2.1e+12]])]

In [51]:
kelemental[2]

array([[0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00],
       [0.0e+00, 2.1e+12, 0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00, 2.1e+12]])