In [1]:
import numpy as np
np.set_printoptions(precision=2, linewidth=100)

In [2]:
M = np.random.rand(6,6)

In [3]:
M

array([[0.62, 0.4 , 0.59, 0.69, 0.82, 0.81],
       [0.49, 0.88, 0.06, 0.41, 1.  , 0.15],
       [0.95, 0.52, 0.83, 0.89, 0.34, 0.47],
       [0.8 , 0.95, 0.5 , 0.2 , 0.08, 1.  ],
       [0.51, 0.08, 0.43, 0.7 , 0.49, 0.83],
       [0.37, 0.67, 0.  , 0.12, 0.69, 0.63]])

In [4]:
M[0:1,2:3]

array([[0.59]])

In [5]:
for i in [0,1,2]:
    for j in [0,1,2]:
        I  = [2*i, 2*i+1] #np.linspace(2*i, 2*i+1, 2)#[0,1]
        J  = [2*j, 2*j+1]
        print('I : ', I, 'J: ', J)
        print( M [np.ix_(I, J)] )
        print('-------------------')

I :  [0, 1] J:  [0, 1]
[[0.62 0.4 ]
 [0.49 0.88]]
-------------------
I :  [0, 1] J:  [2, 3]
[[0.59 0.69]
 [0.06 0.41]]
-------------------
I :  [0, 1] J:  [4, 5]
[[0.82 0.81]
 [1.   0.15]]
-------------------
I :  [2, 3] J:  [0, 1]
[[0.95 0.52]
 [0.8  0.95]]
-------------------
I :  [2, 3] J:  [2, 3]
[[0.83 0.89]
 [0.5  0.2 ]]
-------------------
I :  [2, 3] J:  [4, 5]
[[0.34 0.47]
 [0.08 1.  ]]
-------------------
I :  [4, 5] J:  [0, 1]
[[0.51 0.08]
 [0.37 0.67]]
-------------------
I :  [4, 5] J:  [2, 3]
[[0.43 0.7 ]
 [0.   0.12]]
-------------------
I :  [4, 5] J:  [4, 5]
[[0.49 0.83]
 [0.69 0.63]]
-------------------


In [6]:
M[np.ix_([0,1],[2,3])]

array([[0.59, 0.69],
       [0.06, 0.41]])

In [7]:
M3 = np.random.rand(8,8)

In [8]:
M3

array([[0.81, 0.33, 0.6 , 0.4 , 0.91, 0.06, 0.23, 0.58],
       [0.6 , 0.07, 0.4 , 0.56, 0.93, 0.86, 0.3 , 0.6 ],
       [0.42, 0.05, 0.3 , 0.36, 0.66, 0.44, 0.85, 0.39],
       [0.92, 0.95, 0.95, 0.95, 0.56, 0.01, 0.04, 0.44],
       [0.26, 0.47, 0.6 , 0.04, 0.24, 0.92, 0.38, 0.92],
       [0.34, 0.73, 0.34, 0.26, 0.62, 0.03, 0.73, 0.96],
       [0.15, 0.81, 0.92, 0.26, 0.74, 0.89, 0.63, 0.45],
       [0.45, 0.26, 0.73, 0.93, 0.29, 0.96, 0.08, 0.9 ]])

In [9]:
for i in [0,1]:
    for j in [0,1]:
        I  = np.linspace(4*i, 4*(i+1)-1, 4).astype(int) #np.linspace(2*i, 2*i+1, 2)#[0,1]
        J  = np.linspace(4*j, 4*(j+1)-1, 4).astype(int) #[2*j, 2*j+1]
        print('I : ', I, '; J: ', J)
        print( M3 [np.ix_(I, J)] )
        print('-------------------')

I :  [0 1 2 3] ; J:  [0 1 2 3]
[[0.81 0.33 0.6  0.4 ]
 [0.6  0.07 0.4  0.56]
 [0.42 0.05 0.3  0.36]
 [0.92 0.95 0.95 0.95]]
-------------------
I :  [0 1 2 3] ; J:  [4 5 6 7]
[[0.91 0.06 0.23 0.58]
 [0.93 0.86 0.3  0.6 ]
 [0.66 0.44 0.85 0.39]
 [0.56 0.01 0.04 0.44]]
-------------------
I :  [4 5 6 7] ; J:  [0 1 2 3]
[[0.26 0.47 0.6  0.04]
 [0.34 0.73 0.34 0.26]
 [0.15 0.81 0.92 0.26]
 [0.45 0.26 0.73 0.93]]
-------------------
I :  [4 5 6 7] ; J:  [4 5 6 7]
[[0.24 0.92 0.38 0.92]
 [0.62 0.03 0.73 0.96]
 [0.74 0.89 0.63 0.45]
 [0.29 0.96 0.08 0.9 ]]
-------------------


# Lectura de datos de un archivo
 y escritura

In [10]:
np.savetxt('M3_randdom.dat', M3, fmt='%8.3f')

In [11]:
M3R = np.loadtxt('M3_randdom.dat')

In [12]:
M3R

array([[0.81, 0.33, 0.6 , 0.4 , 0.91, 0.06, 0.23, 0.58],
       [0.6 , 0.07, 0.4 , 0.56, 0.93, 0.86, 0.3 , 0.6 ],
       [0.42, 0.05, 0.3 , 0.36, 0.66, 0.44, 0.85, 0.39],
       [0.92, 0.95, 0.95, 0.95, 0.56, 0.01, 0.04, 0.44],
       [0.26, 0.47, 0.6 , 0.04, 0.24, 0.92, 0.38, 0.92],
       [0.34, 0.73, 0.34, 0.26, 0.62, 0.03, 0.73, 0.96],
       [0.15, 0.81, 0.92, 0.27, 0.74, 0.9 , 0.63, 0.45],
       [0.46, 0.27, 0.73, 0.93, 0.29, 0.96, 0.08, 0.9 ]])

In [13]:
with open('M3_randdom.dat', 'r') as f:
    M3COPY = f.readlines()

In [15]:
M3COPY

['   0.814    0.331    0.597    0.402    0.912    0.061    0.235    0.580\n',
 '   0.601    0.066    0.397    0.565    0.933    0.860    0.301    0.596\n',
 '   0.416    0.051    0.302    0.356    0.660    0.444    0.846    0.390\n',
 '   0.917    0.947    0.949    0.955    0.565    0.015    0.044    0.441\n',
 '   0.258    0.468    0.599    0.044    0.242    0.915    0.378    0.924\n',
 '   0.337    0.728    0.337    0.258    0.618    0.026    0.733    0.958\n',
 '   0.151    0.811    0.916    0.265    0.740    0.895    0.630    0.447\n',
 '   0.455    0.265    0.731    0.929    0.292    0.956    0.084    0.898\n']

In [22]:
import re

In [30]:
M3NUMS = []
for line in M3COPY:
    fila = re.split('\s+', line.strip())
    print(fila)
#   filanum = []
#   for f in fila:
#       filanum.append(float(f))
    filanum = [float(f) for f in fila]
    print(filanum)
    M3NUMS.append(filanum)

['0.814', '0.331', '0.597', '0.402', '0.912', '0.061', '0.235', '0.580']
[0.814, 0.331, 0.597, 0.402, 0.912, 0.061, 0.235, 0.58]
['0.601', '0.066', '0.397', '0.565', '0.933', '0.860', '0.301', '0.596']
[0.601, 0.066, 0.397, 0.565, 0.933, 0.86, 0.301, 0.596]
['0.416', '0.051', '0.302', '0.356', '0.660', '0.444', '0.846', '0.390']
[0.416, 0.051, 0.302, 0.356, 0.66, 0.444, 0.846, 0.39]
['0.917', '0.947', '0.949', '0.955', '0.565', '0.015', '0.044', '0.441']
[0.917, 0.947, 0.949, 0.955, 0.565, 0.015, 0.044, 0.441]
['0.258', '0.468', '0.599', '0.044', '0.242', '0.915', '0.378', '0.924']
[0.258, 0.468, 0.599, 0.044, 0.242, 0.915, 0.378, 0.924]
['0.337', '0.728', '0.337', '0.258', '0.618', '0.026', '0.733', '0.958']
[0.337, 0.728, 0.337, 0.258, 0.618, 0.026, 0.733, 0.958]
['0.151', '0.811', '0.916', '0.265', '0.740', '0.895', '0.630', '0.447']
[0.151, 0.811, 0.916, 0.265, 0.74, 0.895, 0.63, 0.447]
['0.455', '0.265', '0.731', '0.929', '0.292', '0.956', '0.084', '0.898']
[0.455, 0.265, 0.731, 0

In [29]:
M3NUMS

[[0.814, 0.331, 0.597, 0.402, 0.912, 0.061, 0.235, 0.58],
 [0.601, 0.066, 0.397, 0.565, 0.933, 0.86, 0.301, 0.596],
 [0.416, 0.051, 0.302, 0.356, 0.66, 0.444, 0.846, 0.39],
 [0.917, 0.947, 0.949, 0.955, 0.565, 0.015, 0.044, 0.441],
 [0.258, 0.468, 0.599, 0.044, 0.242, 0.915, 0.378, 0.924],
 [0.337, 0.728, 0.337, 0.258, 0.618, 0.026, 0.733, 0.958],
 [0.151, 0.811, 0.916, 0.265, 0.74, 0.895, 0.63, 0.447],
 [0.455, 0.265, 0.731, 0.929, 0.292, 0.956, 0.084, 0.898]]

In [31]:
with open('M3WRITE.dat', 'w') as f:
    f.writelines(M3COPY)

# Lectura secuencial

In [32]:
f = open('M3_randdom.dat', 'r')

In [33]:
f

<_io.TextIOWrapper name='M3_randdom.dat' mode='r' encoding='UTF-8'>

In [34]:
line1 =  f.readline()

In [49]:
linea1_nums = [float(f) for f in re.split('\s+',line1.strip())]

In [43]:
linea1_nums

[0.814, 0.331, 0.597, 0.402, 0.912, 0.061, 0.235, 0.58]

In [44]:
line2 = f.readline()

In [45]:
line2

'   0.601    0.066    0.397    0.565    0.933    0.860    0.301    0.596\n'

In [50]:
linea2_nums = [float(f) for f in re.split('\s+',line2.strip())]

In [51]:
linea2_nums

[0.601, 0.066, 0.397, 0.565, 0.933, 0.86, 0.301, 0.596]

In [52]:
f.close()

# Repetir hasta el final del archivo

In [56]:
Nums = []
with open('M3_randdom.dat','r') as f:
    for line in f:
        print(type(line))
        linea_nums = [float(f) for f in re.split('\s+',line.strip())]
        Nums.append(linea_nums)
        

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [57]:
Nums

[[0.814, 0.331, 0.597, 0.402, 0.912, 0.061, 0.235, 0.58],
 [0.601, 0.066, 0.397, 0.565, 0.933, 0.86, 0.301, 0.596],
 [0.416, 0.051, 0.302, 0.356, 0.66, 0.444, 0.846, 0.39],
 [0.917, 0.947, 0.949, 0.955, 0.565, 0.015, 0.044, 0.441],
 [0.258, 0.468, 0.599, 0.044, 0.242, 0.915, 0.378, 0.924],
 [0.337, 0.728, 0.337, 0.258, 0.618, 0.026, 0.733, 0.958],
 [0.151, 0.811, 0.916, 0.265, 0.74, 0.895, 0.63, 0.447],
 [0.455, 0.265, 0.731, 0.929, 0.292, 0.956, 0.084, 0.898]]

In [58]:
import pickle

In [61]:
with open('MyVars.pkl', 'wb') as f:
    pickle.dump(Nums, f)
    pickle.dump(M3NUMS,f)

In [62]:
with open('MyVars.pkl', 'rb') as f:
    NumsCopy = pickle.load(f)

In [63]:
NumsCopy

[[0.814, 0.331, 0.597, 0.402, 0.912, 0.061, 0.235, 0.58],
 [0.601, 0.066, 0.397, 0.565, 0.933, 0.86, 0.301, 0.596],
 [0.416, 0.051, 0.302, 0.356, 0.66, 0.444, 0.846, 0.39],
 [0.917, 0.947, 0.949, 0.955, 0.565, 0.015, 0.044, 0.441],
 [0.258, 0.468, 0.599, 0.044, 0.242, 0.915, 0.378, 0.924],
 [0.337, 0.728, 0.337, 0.258, 0.618, 0.026, 0.733, 0.958],
 [0.151, 0.811, 0.916, 0.265, 0.74, 0.895, 0.63, 0.447],
 [0.455, 0.265, 0.731, 0.929, 0.292, 0.956, 0.084, 0.898]]