In [1]:
import numpy as np
A=np.array(
    [
        [1,-3,-2],
        [2,-4,-3],
        [-3,6,8]
    ]
)
b=np.array([[6],[8],[-5]])



In [2]:
print(A)
print(b)

[[ 1 -3 -2]
 [ 2 -4 -3]
 [-3  6  8]]
[[ 6]
 [ 8]
 [-5]]


In [3]:
x=np.linalg.solve(A,b)

In [5]:
print(x)

[[ 1.]
 [-3.]
 [ 2.]]


In [8]:
A.dot(x)-b

array([[0.],
       [0.],
       [0.]])