# Introducción a Python

Lo primero que hacemos siempre es improtar las librerís que vamos a necesitar

In [1]:
# Importo las librerías Necesarias 
import numpy as np  # Importo algebra Lineal
import matplotlib.pyplot as plt # Importo librería de gráficos

# Tipos de Variables

 En __python__ las variables no necesitan ser decalaradas. Pueden usarse  variables de varios tipos:
 
 - punto flotante, 
 - números enteros,
 - texto o cadenas de caracteres.
 
 __Python__ es un lenguaje no compilable orientado a objetos. Por el momento nos concentramos en los aspectos básicos y retomaremos el concepto más tarde. 

Cualquier objeto puede asignarse con el operador de asignación `=`. 

In [2]:
A = 1

In [3]:
B ='Mi Variable'

In [4]:
C = np.pi

In [5]:
print(B, C , '!= ', A)

Mi Variable 3.141592653589793 !=  1


vemos así la sentencia `print` que nos permite imprimir una o mas variables. 

## Iterables

Los objetoa **iterables**  son los que tienen varios elementos y se los puede ciclar. El primer ejemplo son las _listas_:

In [6]:
L = [1,2,3,np.pi, A, B, C,  [ A, B, C]]

Vemos que las listas pueden tener objetos de distintos tipos, incluso otras listas. La manera de acceder a sus objetos es indexándolas. Debemos saber que el primer elemento de una liste tiene el índice 0


In [7]:
L[0]

1

mientras que al último elemento se puede acceder con el índice `-1`

In [8]:
L[-1]

[1, 'Mi Variable', 3.141592653589793]

tambíen podemos tomar un grupo de elementos mediante _slicing_:

In [9]:
L[0:3]

[1, 2, 3]

notar qe los rangos de indices de la forma `i:j` no incluyen el límite superior.

hay otros iterables que puede investigar: los tuples y las cadenas de caracteres se comportan de esta manera. 

## Matrices

Los elementos numéricos como las matrices necesitan de la librería de álgebra lineal `numpy` para serdefinidos:

In [10]:
I = np.array(
    [
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]
    ]
)

notar que una matriz de dos dimensiones es una lista , que contene una lista por cada fila, cada una de los cuales contiene tantos elementos como columnas. 

Para generar un vector columna:

In [11]:
col = np.array([[1],[2],[3]])

In [12]:
col

array([[1],
       [2],
       [3]])

La multiplicación de matrices se realiza con el método dot, que tienen todos los elementos np.array:

In [13]:
I.dot(col)

array([[1],
       [2],
       [3]])

In [14]:
I.dot(I)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [15]:
col*col

array([[1],
       [4],
       [9]])

# Objetos

Un _objeto_ es, al igual que un objeto físico, una entidad a la que se le pueden definir propiedades y con la cual se pueden realizar operaciones. En __python__ los objetos se definen como clases, y se puede acceder a sus propiedades con el operador punto una vez que han sido instanciados. 


In [16]:
class MiCuadrilatero:
    
    def __init__(self, largo, alto):
        # inicio las propiedades
        self.largo = largo
        self.alto = alto
        
    # defino métodos del objeto para obtener más propiedades:
    
    def get_area(self):
        self.area = self.largo * self.alto
        
    def deformar(self, factor):
        
        self.largo = self.largo*factor
        
        self.alto = self.alto*factor
        
        print('Cuidado: debe recalcular el área')
        
        

In [17]:
UnCuadrado = MiCuadrilatero(1,1)
UnRectangulo = MiCuadrilatero(1,2)
from scipy.constants import golden_ratio
UnRectanguloHermoso = MiCuadrilatero(1,golden_ratio)
UnCuadrado.get_area()
UnRectangulo.get_area()
UnRectanguloHermoso.get_area()
print(UnCuadrado.area, UnRectangulo.area, UnRectanguloHermoso.area)

1 2 1.618033988749895


# Markdown

En las celdas`Markdown` es posible insertar texto con formato. podemos usar comandos al estilo latex para insertar ecuaciones. ¡No se asuste!, dice la guía, es realmente muy fácil:

$ S = \sum_{1}^{\infty} \frac{1}{n^2} $


$ S = 1 + \frac{1}{4} + \frac{1}{9} + ...  $

## Control de Flujo

Tomemos esta serie para practicar un poco:

In [18]:
# 1/n**2
S = 1 + 1/4 + 1/9 + 1/16 + 1/25 + 1/36 + 1/7**2 + 1/8**2

In [19]:
S

1.527422052154195

Tratemos de tomas en forma automática tantos términos en la seria como sea necesario:

In [20]:
S = 0

for i in range(1,100):
    Sout = S
    S += 1/i**2
    e = np.abs((Sout-S)/S)
    print('el valor de e es: ', e , 'en el paso ', i)
    if e < 1e-3:
        print('la serie conver(gj)e en ', i, 'pasos')
        break

print('el valor final de S es:', S)

el valor de e es:  1.0 en el paso  1
el valor de e es:  0.2 en el paso  2
el valor de e es:  0.08163265306122452 en el paso  3
el valor de e es:  0.04390243902439024 en el paso  4
el valor de e es:  0.027329664072879126 en el paso  5
el valor de e es:  0.018625442354255846 en el paso  6
el valor de e es:  0.013499274414000263 en el paso  7
el valor de e es:  0.01022965458562244 en el paso  8
el valor de e es:  0.008017883972014757 en el paso  9
el valor de e es:  0.006452579827864148 en el paso  10
el valor de e es:  0.005304423645332071 en el paso  11
el valor de e es:  0.0044374109325053725 en el paso  12
el valor de e es:  0.003766747166583278 en el paso  13
el valor de e es:  0.0032373440906811454 en el paso  14
el valor de e es:  0.0028121558852933263 en el paso  15
el valor de e es:  0.0024655275329862904 en el paso  16
el valor de e es:  0.002179237260418972 en el paso  17
el valor de e es:  0.0019400546995336633 en el paso  18
el valor de e es:  0.0017381859769140975 en el paso

como vimos, la sentencia `for` nos permite iterar en un contador en un rango. la sentencia `range` nos gerena un objeto iterador que toma valores entre el límite inferior y sin incluir el límite superior. Si el límite inferior no se da explícitamente, se usa el cero. 

Boremos las variables generadas:

In [21]:
del e, S, Sout

Y reinventemos el mundo:

In [22]:
e = [1]
S = [1]
i = 1
while e[-1] > 1e-100:
    i += 1
    S.append( S[-1] + 1/i**2 )
    e.append( np.abs((S[-2]-S[-1])/S[-1]) )
    if i > 100:
        print('la serie no converge')
        break

la serie no converge


lo que hicimos con el código anterior es lo mismo de antes , pero la sentencia `while` itera el código hasta que la condición lógica que la condiciona retorna `False`. 

En el ejemplpo definimos las listas `e` t `S` y manipulamos sus elementos para almacenar  los errores y las sumas parciales en cada paso. La iteración se realiza solo si el error es más grande que una tolerancia (en este caso ridículamente exigente) y se pone el condicional if que rompe la iteración (`break`) si se han realizado más de 100 vueltas

In [23]:
S

[1,
 1.25,
 1.3611111111111112,
 1.4236111111111112,
 1.4636111111111112,
 1.4913888888888889,
 1.511797052154195,
 1.527422052154195,
 1.5397677311665408,
 1.5497677311665408,
 1.558032193976458,
 1.5649766384209025,
 1.5708937981842162,
 1.5759958390005426,
 1.580440283444987,
 1.584346533444987,
 1.587806741057444,
 1.5908931608105303,
 1.5936632439130234,
 1.5961632439130233,
 1.5984308176091684,
 1.6004969333116477,
 1.6023872924798896,
 1.6041234035910008,
 1.6057234035910009,
 1.6072026935318293,
 1.6085744356443121,
 1.6098499458483937,
 1.6110390064904865,
 1.6121501176015975,
 1.6131907003279242,
 1.6141672628279242,
 1.6150855364734706,
 1.6159505883765848,
 1.616766914907197,
 1.6175385198454686,
 1.6182689800353882,
 1.6189615008110114,
 1.619618963006935,
 1.6202439630069352,
 1.6208388470045556,
 1.621405740428592,
 1.6219465733112313,
 1.6224631022368512,
 1.622956929397345,
 1.6234295191894055,
 1.623882212715888,
 1.6243162404936657,
 1.6247327336215291,
 1.6251327336

In [24]:
plt.rc('figure', figsize=(15,15))
plt.rc('axes',labelsize=28)
plt.rc('xtick',labelsize=28)
plt.rc('ytick',labelsize=28)

In [25]:
plt.plot(S)
plt.xlabel('i')
plt.ylabel('S')
plt.axhline(S[-1], ls='--',c='k', lw=5)
t=plt.annotate('S = {:.5f} $\pm$ {:.0e}'.format(S[-1], e[-1]), xy = (0.5, 0.97), xycoords='axes fraction' , fontsize='18')

In [26]:
plt.semilogy(e)
plt.ylabel('e')
plt.xlabel('i')
plt.grid()

El comando `plot` de la librería `numpy` nos permite graficar listas o array, o mas en gerenal cualquier iterable que contenga números reales. El error lo graficamos en escala semilogarítmica para comparar escalas discímiles.