# Problema 5

In [1]:
import numpy as np

definimos la matriz del sistema

In [5]:
A = np.array(  
    [ [1, -3, -2],   [ 2, -4, -3],   [-3, 6, 8  ]   ]
)

In [6]:
A

array([[ 1, -3, -2],
       [ 2, -4, -3],
       [-3,  6,  8]])

el vector columna de soluciones:

In [20]:
B = np.array( [ [6], [8], [-5] ] )

In [8]:
B

array([[ 6],
       [ 8],
       [-5]])

Podríamos  por ejemplo __transponer__ usando el método `transpose` de cualquier objeto `np.array`

In [10]:
C = B.transpose()

In [11]:
C

array([[ 6,  8, -5]])

Pero notar que este objeto sigue siendo 2D

In [12]:
B.shape

(3, 1)

In [13]:
C.shape

(1, 3)

In [14]:
D = np.array([6,8,-5])

In [15]:
D.shape

(3,)

In [16]:
D.transpose()

array([ 6,  8, -5])

Cidado ! Un objeto 1D no se puede transponer tan fácil, hay que hacer _reshape_

In [17]:
D.reshape(-1,1)

array([[ 6],
       [ 8],
       [-5]])

Podemos resolver el sistema lineal fácilmente con `np.linalg.solve`

In [21]:
X = np.linalg.solve(A, B)


En matlab hacíamos:
```
X = A\B
X = inv(A)*B
```

El resultado

In [22]:
X

array([[ 1.],
       [-3.],
       [ 2.]])

# Código más compacto:

In [27]:
A = np.array(  
    [ [1, -3, -2],   [ 2, -4, -3],   [-3, 6, 8  ]   ]
)

B = np.array( [ [6], [8], [-5] ] )

X = np.linalg.solve(A, B)

In [28]:
X

array([[ 1.],
       [-3.],
       [ 2.]])